### ISSUE TITLE
Telegram and fpJSON bug

### ISSUE THREAD

**Issue by nicolasmdq** [Al-Muhandis/fp-telegram#4]
Hi! First of all: Great work with your library! Thank to your work I've created a TG bot, unfortunately after the 3.2.0 update my bot has problems receiving TG text.

After several hours of investigation, TG doesn't send UTF8 text. Instead, it sends escaped chars just like \u00f1 (Spanish ñ). That's valid and correct for JSON, but fpJSON returns ? (a question mark, possibly because trying to direct convert to UTF8?), it's clearly a bug in fpJSON.

By now, I've modified TTelegramSender.StringToJSONObject to "disable" UTF8 until FP team fixes it.

class function TTelegramSender.StringToJSONObject(const AString: String): TJSONObject;
var
  lParser: TJSONParser;
  Options: TJSonOptions;
begin
  Result := nil;
  if AString<>EmptyStr then
  begin
    Options:= DefaultOptions;
    Exclude(Options,joUTF8);
    lParser := TJSONParser.Create(AString{$IF FPC_FULLVERSION > 30002}, Options{$ENDIF});
....
PS: I'm new on GitHub, I don't want to make a pull request without your checking... Thank you!!!

**Comment by Al-Muhandis** [comment]
Hi! Thanks.
1. Do You use the latest version of the library? OPM and release is not last commited repo. Try to use immediatly the source There is a new commit due 3.2.0 release couple days ago
2. In previous versions of the fpJSON library there was a problem with decoding Emoji https://bugs.freepascal.org/view.php?id=32670 but at least at 3.2.0 this fixed. Perhaps this is somehow related?
3. I tried to reproduce Your error, but I haven't found any problems yet. There were problems in previous versions of FPC. Do You fp-telegram [tests ](https://github.com/Al-Muhandis/fp-telegram/tree/master/test) pass? Try experimenting with the TestSendMessage test. Perhaps You have a specific case. What OS do You have? Does the error only appear with Spanish? Is it possible that the String string incorrectly defines the encoding when receiving text in the program from the outside?
4. I will add your suggestion, but close it with the compiler option. Since I'm afraid this may cause encoding problems for other users. For example, `{$ifdef JsonNoUTF8}`... ...`{$end}` To use the hack, you will need to add the compiler key `-dJsonNoUTF8` on the Custom options tab in the project compilation properties. Will this suit You?

P.S.
However, I would like to get more information about the conditions of the bug. Can you test it on tests or make a minimal example?

**Comment by Al-Muhandis** [comment]
See last commit https://github.com/Al-Muhandis/fp-telegram/blob/a2d2aec067a7de7b4e8eeb252f920dff99ae10b4/tgsendertypes.pas#L1745

**Comment by nicolasmdq** [comment]
Hi, in my case use FPC 3.2.0 console (No Lazarus) under **Windows 10**. Console codepage is 850 and system codepage is 1252.

Using latest version of library makes no difference with FPC 3.2.0 or 3.3.1. Until 3.0.4 all is working fine. Problem is related somehow to point 2. Using tests makes the same result: ? instead ñ. 

After several tests, I've found JSON parsing somewhat strange... because if I use {$ifdef JsonNoUTF8} ñ is received fine. I want to share my tests illustating the issue (Note: #195#177 is UTF8 version of ñ, and body2 is ñ like received by Telegram):

Uses FPJSon,jsonparser;
Var
JSON: ShortString;
O: TJSONObject;
Begin
JSON:= '{"body":"'+#195#177+'","body2":"\u00f1"}';
O:= TJSONObject(GetJSON(JSON));
WriteLn(O.FindPath('body').asString);
WriteLn(O.FindPath('body2').asString);
WriteLn(JSONStringToString('\u00f1'));
O.Free;
End.

Returns (3.2.0):
ñ    (body)
?    (body2)
ñ    (JSONStringToString)

In 3.0.4 it returns:
?   (body)
ñ  (body2)        
ñ  (JSONStringToString)

Thats why in 3.0.4 FP-Telegram works excellent for me! What's the change here? JSON parsing has changed and now is more system codepage dependant. 

Easy solution or me without changing FP-Telegram is to add

SetMultiByteConversionCodePage(CP_UTF8);

at the beginning of my bot app so fpJSON works as expected (and so FP-Telegram) under Windows. Finally, tests results are (3.0.4 and 3.2.0):

ñ
ñ
ñ

Thank you again and great work!

**Comment by Al-Muhandis** [comment]
> because if I use {$ifdef JsonNoUTF8} ñ is received fine

Are You means: if use -dJsonNoUTF8 is added for program? So I used this key to enable the hack you suggested for the library. 

> I want to share my tests illustating the issue (Note: #195#177 is UTF8 version of ñ, and body2 is ñ like received by Telegram):

I understand You. But **all three options** give me valid results in various FPC versions in Windows 10 or Linux (no any "?"). And one important nuance: **I compiled this code in Lazarus IDE**



> Easy solution or me without changing FP-Telegram is to add
> 
> SetMultiByteConversionCodePage(CP_UTF8);

So, The problem is solved? I will not cancel the last commit yet, especially since the hack is enabled only when using a special compilation key.

**Comment by nicolasmdq** [comment]
> Are You means: if use -dJsonNoUTF8 is added for program? So I used this key to enable the hack you suggested for the library.

Yes, sorry, my bad. I mean compile with {$define JsonNoUTF8} because I was debugging the issue through **FP IDE**.

> So, The problem is solved? I will not cancel the last commit yet, especially since the hack is enabled only when using a special compilation key.

Yes, with SetMultiByteConversionCodePage(CP_UTF8) fpJSON returns correct values and my issue was solved. My bot is working fine! Hack can be useful anyway, because cp1252 is default in standard Windows on Latin America (idk if you have 1252 too) and SetMultiByteConversionCodePage(CP_UTF8) could not to be always a good choice.

**Comment by nicolasmdq** [comment]
PS: Can you add a function for me? I'm new on GitHub, and I need a "sendPhotoStream" which let me define ParseMode as pmHTML:

function TTelegramSender.sendPhotoStream(chat_id: Int64; const AFileName: String;
  APhotoStream: TStream; const ACaption: String; ParseMode: TParseMode = pmDefault; ReplyMarkup: TReplyMarkup = nil): Boolean;
var
  sendObj: TStringList;
begin
  Result:=False;
  sendObj:=TStringList.Create;
  with sendObj do
  try
    Add(s_ChatId+'='+IntToStr(chat_id));
    if ACaption<>EmptyStr then
      Add(s_Caption+'='+ACaption);
    if ParseMode<>pmDefault then
      Add(s_ParseMode+'='+ParseModes[ParseMode]);
    if Assigned(ReplyMarkup) then
      Add(s_ReplyMarkup+'='+ReplyMarkup.AsJSON);
    Result:=SendStream(s_sendPhoto, s_Photo, AFileName, APhotoStream, sendObj);
  finally
    Free;
  end;
end;

Thank you!

**Comment by Al-Muhandis** [comment]
> PS: Can you add a function for me? I'm new on GitHub, and I need a "sendPhotoStream" which let me define ParseMode

Yes, of course https://github.com/Al-Muhandis/fp-telegram/commit/a1420297ba5aaadf12ba7de28f5a6df8b5f03883 . And YOu can make pullrequest. It can do it via web github interface even. Just edit source. Then create pullrequest

**Comment by nicolasmdq** [comment]
Thank you very much!
